src/main/kotlin/no/fdk/dataset_catalog/rdf/Namespace.kt
src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt
src/main/kotlin/no/fdk/dataset_catalog/service/RDFService.kt
src/test/resources/catalog_2.ttl

fix: use correct hasBody in dqv:hasQualityAnnotation

---

src/main/kotlin/no/fdk/dataset_catalog/Application.kt
src/main/kotlin/no/fdk/dataset_catalog/model/Dataset.kt
src/main/kotlin/no/fdk/dataset_catalog/service/ConceptService.kt
src/main/resources/application.yml

fix: #75 ignor unknown properties in ContactPoint

---

src/main/kotlin/no/fdk/dataset_catalog/controller/RDFController.kt
src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFDatasetUtils.kt
src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt
src/main/kotlin/no/fdk/dataset_catalog/service/DatasetService.kt
src/main/kotlin/no/fdk/dataset_catalog/service/RDFService.kt
src/test/kotlin/no/fdk/dataset_catalog/contract/RdfContractTest.kt
src/test/kotlin/no/fdk/dataset_catalog/service/DatasetServiceTest.kt
src/test/kotlin/no/fdk/dataset_catalog/service/RdfServiceTest.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestData.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestDataset_1.kt
src/test/resources/catalog_2.ttl
src/test/resources/dataset.ttl
src/test/resources/getAll.ttl

rm brreg uri as default dataset-uri & add dataset turtle endpoint

---

src/main/kotlin/no/fdk/dataset_catalog/controller/RDFController.kt
src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt
src/main/kotlin/no/fdk/dataset_catalog/security/SecurityConfig.kt
src/test/kotlin/no/fdk/dataset_catalog/contract/RdfContractTest.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestUtils.kt

feat: accept more rdf-types

---

src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt
src/test/resources/catalog_2.ttl

chore: serialize access services as uris

---

README.md
src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt
src/test/kotlin/no/fdk/dataset_catalog/rdf/RDFDatasetUtilsTest.kt

fix: distribution null check

---

README.md
src/main/resources/application.yml

chore: improve configuration

---

src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFDatasetUtils.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestUtils.kt
src/test/resources/catalog_0.ttl
src/test/resources/catalog_1.ttl
src/test/resources/catalog_2.ttl
src/test/resources/dataset.ttl
src/test/resources/getAll.ttl
src/test/resources/getOne.ttl

fix: dct:identifier as Literal

---

src/main/kotlin/no/fdk/dataset_catalog/controller/CatalogController.kt
src/main/kotlin/no/fdk/dataset_catalog/extensions/CatalogExtensions.kt
src/main/kotlin/no/fdk/dataset_catalog/model/Catalog.kt
src/main/kotlin/no/fdk/dataset_catalog/service/CatalogService.kt
src/main/resources/specification/specification.yaml
src/test/kotlin/no/fdk/dataset_catalog/contract/CatalogContractTest.kt
src/test/kotlin/no/fdk/dataset_catalog/service/CatalogServiceTest.kt
src/test/kotlin/no/fdk/dataset_catalog/service/RdfServiceTest.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestData.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestDataset_0.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestDataset_1.kt

add dataset count to catalog response

---

pom.xml
src/main/kotlin/no/fdk/dataset_catalog/configuration/JacksonConfigurer.kt
src/main/kotlin/no/fdk/dataset_catalog/controller/DatasetController.kt
src/main/kotlin/no/fdk/dataset_catalog/extensions/DatasetExtensions.kt
src/main/kotlin/no/fdk/dataset_catalog/model/Dataset.kt
src/main/kotlin/no/fdk/dataset_catalog/model/JsonPatch.kt
src/main/kotlin/no/fdk/dataset_catalog/service/DatasetService.kt
src/main/resources/specification/specification.yaml
src/test/kotlin/no/fdk/dataset_catalog/contract/DatasetContractTest.kt
src/test/kotlin/no/fdk/dataset_catalog/service/DatasetServiceTest.kt

RFC6092 compliant patch

---

src/main/kotlin/no/fdk/dataset_catalog/configuration/ApplicationProperties.kt
src/main/kotlin/no/fdk/dataset_catalog/service/CatalogService.kt
src/main/kotlin/no/fdk/dataset_catalog/service/OrganizationService.kt
src/main/resources/application.yml

resolve https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/616

fix: use organization-catalog env

---

src/main/kotlin/no/fdk/dataset_catalog/service/DatasetService.kt

Fixes https://github.com/Informasjonsforvaltning/dataset-catalog/issues/126

fix: do not include catalogid when checking dataset uri

---

src/main/kotlin/no/fdk/dataset_catalog/model/Dataset.kt
src/main/kotlin/no/fdk/dataset_catalog/service/DatasetService.kt
src/main/resources/specification/specification.yaml
src/test/kotlin/no/fdk/dataset_catalog/service/DatasetServiceTest.kt

feat: specify specialized type for datasets on create

---

src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt

fix: check lang values when validation relations

---

src/main/kotlin/no/fdk/dataset_catalog/controller/DatasetController.kt
src/main/kotlin/no/fdk/dataset_catalog/model/Dataset.kt
src/main/kotlin/no/fdk/dataset_catalog/repository/DatasetRepository.kt
src/main/kotlin/no/fdk/dataset_catalog/service/DatasetService.kt
src/main/kotlin/no/fdk/dataset_catalog/service/PublishingService.kt
src/test/kotlin/no/fdk/dataset_catalog/contract/CatalogContractTest.kt
src/test/kotlin/no/fdk/dataset_catalog/contract/SeriesContractTest.kt
src/test/kotlin/no/fdk/dataset_catalog/service/DatasetServiceTest.kt
src/test/kotlin/no/fdk/dataset_catalog/service/PublishingServiceTest.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestData.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/jwk/JwtToken.kt
src/test/resources/getAll.ttl

resolve #111 
resolve #136
Jeg gikk for å lagre listen som en map, så kan blir sorteringen etter int-indeksen. Da er vi veldig spesifikke på akkurat hva sorteringen skal være

feat: add inSeries for datasets

---

src/main/kotlin/no/fdk/dataset_catalog/model/Dataset.kt
src/main/kotlin/no/fdk/dataset_catalog/service/DatasetService.kt
src/test/kotlin/no/fdk/dataset_catalog/contract/SeriesContractTest.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestData.kt

chore: only support one series membership for each dataset

---

src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFDatasetUtils.kt
src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt
src/main/kotlin/no/fdk/dataset_catalog/service/DatasetService.kt
src/main/kotlin/no/fdk/dataset_catalog/service/RDFService.kt
src/test/kotlin/no/fdk/dataset_catalog/contract/CatalogContractTest.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestData.kt
src/test/resources/getAll.ttl

feat: include dataset series in rdf response

---

src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFDatasetUtils.kt
src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt

fix: only add relevant fields when creating rdf for series

---

src/main/kotlin/no/fdk/dataset_catalog/service/OrganizationService.kt

fix: validate orgnr

---

src/main/kotlin/no/fdk/dataset_catalog/model/Dataset.kt
src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt
src/main/resources/specification/specification.yaml
src/test/kotlin/no/fdk/dataset_catalog/utils/TestDataset_0.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestDataset_1.kt
src/test/resources/catalog_2.ttl

Fixes https://github.com/Informasjonsforvaltning/dataset-catalog/issues/159

feat: add distribution dcat:mediaType attribute

---

src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFDatasetUtils.kt
src/test/resources/getAll.ttl

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/755

fix: add series properies as linked data

---

.github/workflows/deploy-prod&demo.yaml
.github/workflows/deploy-staging.yaml
deploy/base/dataset-catalog-deployment.yaml
deploy/base/dataset-catalog-service.yaml
deploy/base/kustomization.yaml
deploy/demo/env.yaml
deploy/demo/kustomization.yaml
deploy/prod/env.yaml
deploy/prod/kustomization.yaml
deploy/staging/env.yaml
deploy/staging/kustomization.yaml

feat: add deployment with kustomize

---

src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFDatasetUtils.kt
src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestData.kt
src/test/resources/dataset.ttl
src/test/resources/getAll.ttl
src/test/resources/getOne.ttl

chore: add dataset type to RDF as URI when possible

---

.github/workflows/deploy-prod&demo.yaml
.github/workflows/deploy-staging.yaml
Dockerfile
README.md
deploy/base/kustomization.yaml
deploy/demo/env.yaml
deploy/prod/env.yaml
deploy/staging/env.yaml
pom.xml
src/main/kotlin/no/fdk/dataset_catalog/configuration/SecurityProperties.kt
src/main/kotlin/no/fdk/dataset_catalog/controller/ApplicationStatusController.kt
src/main/kotlin/no/fdk/dataset_catalog/controller/CatalogController.kt
src/main/kotlin/no/fdk/dataset_catalog/controller/DatasetController.kt
src/main/kotlin/no/fdk/dataset_catalog/controller/RDFController.kt
src/main/kotlin/no/fdk/dataset_catalog/controller/SearchController.kt
src/main/kotlin/no/fdk/dataset_catalog/security/SecurityConfig.kt
src/main/resources/application.yml

resolve https://github.com/Informasjonsforvaltning/fdk-team-private/issues/112

chore: update cors config

---

src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt
src/test/resources/catalog_2.ttl

fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/1155

fix: serialize conformsTo as blank nodes

---

deploy/demo/env.yaml
deploy/prod/env.yaml
deploy/staging/env.yaml
docker-compose.yaml
src/main/kotlin/no/fdk/dataset_catalog/extensions/DatasetExtensions.kt
src/main/kotlin/no/fdk/dataset_catalog/model/Dataset.kt
src/main/kotlin/no/fdk/dataset_catalog/model/DatasetDBO.kt
src/main/kotlin/no/fdk/dataset_catalog/rdf/RDFUtils.kt
src/main/kotlin/no/fdk/dataset_catalog/repository/DatasetOperations.kt
src/main/kotlin/no/fdk/dataset_catalog/repository/DatasetRepository.kt
src/main/kotlin/no/fdk/dataset_catalog/service/DatasetService.kt
src/main/kotlin/no/fdk/dataset_catalog/service/SearchService.kt
src/main/resources/application.yml
src/test/kotlin/no/fdk/dataset_catalog/contract/DatasetContractTest.kt
src/test/kotlin/no/fdk/dataset_catalog/contract/PingTest.kt
src/test/kotlin/no/fdk/dataset_catalog/service/DatasetServiceTest.kt
src/test/kotlin/no/fdk/dataset_catalog/service/SearchServiceTest.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestData.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestDataset_0.kt
src/test/resources/dataset.ttl
src/test/resources/getAll.ttl
src/test/resources/getOne.ttl

resolve #215
resolve #218
closes https://github.com/Informasjonsforvaltning/dataset-catalog-gui-old/issues/84
tilhørende ETL: https://github.com/Informasjonsforvaltning/scripts/pull/13

chore: change database and update dataset model

---

src/main/kotlin/no/fdk/dataset_catalog/extensions/DatasetExtensions.kt
src/main/kotlin/no/fdk/dataset_catalog/model/Dataset.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestDataset_0.kt
src/test/kotlin/no/fdk/dataset_catalog/utils/TestDataset_1.kt

part of https://github.com/Informasjonsforvaltning/catalog-frontend/issues/1124

chore: replace organizationUnit with name in contactPoints
